### ISSUE TITLE
operationsFromWSDL and compileHandler args

### ISSUE THREAD

**Issue by MadLord80** [markov2/perl5-XML-Compile-SOAP-Daemon#3]
Why doesn't the operationsFromWSDL() method pass arguments when calling the compileHandler() method?

`$code = $op->compileHandler(callback => $callback);`

I can't, for example, pass the interpret_nillable_as_optional argument to XML::Compile::Translate->compile().
I think the call of  compileHandler() should be like this:
`$code = $op->compileHandler(callback => $callback, %args);`
how is it done in the XML::Compile::SOAP11::Operation->compileHandler() method.

**Comment by markov2** [comment]
I made some changes to the method.  Can you try it?

**Comment by MadLord80** [comment]
Yes, it works. Thanks.
But what about 415 line:
`$code = $op->compileHandler(callback => $callback);`
shouldn't it be necessary to pass arguments here too?

**Comment by markov2** [comment]
> `$code = $op->compileHandler(callback => $callback);`
> shouldn't it be necessary to pass arguments here too?

Eh, of course.  How could it work for you without that change?

**Comment by MadLord80** [comment]
It probably works because I don't use the callbacks array. Only one generic default_callback.

**Comment by markov2** [comment]
Now released in v3.15.  May take some time to seep through to your CPAN mirror
